name: tests-payments

on:
  push:
    paths:
      - 'app/payments/**'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - run: cd app/payments && npm install && npm run test:ci
